openapi: 3.0.0
info:
  description: "UpdateDbQuestion"
  version: 1.0.0
  title: Mobile API for my question
  contact:
    email: stefan@mayer-popp.de
  license:
    name: Propertiary
tags:
  - name: users
    description: Endpoints around the user
paths:
  /users/me:
    get:
      tags:
        - users
      summary: Get user data and profile
      description: "Get user data and profile for current logged in user identified by auth token"
      operationId: getUserData
      parameters:
        - name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: successful operation
          application/json:
            schema:
              type: object
              items:
                $ref: "#/components/schemas/User"
    patch:
      tags:
        - users
      summary: Update user data and profile
      description: "Update user data and profile for given user id"
      operationId: updateUserDataAndProfile
      parameters:
        - name: id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateRequest"
        description: Update user profile
        required: true
      responses:
        "200":
          description: successful operation
          application/json:
            schema:
              type: object
              items:
                $ref: "#/components/schemas/User"
servers:
  - url: http://localhost:3000/api/app/v1
components:
  schemas:
    User:
      type: object
      required:
        - email
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
          example: "user-1@example.com"
          minLength: 3
        user_profile_attributes:
          $ref: "#/components/schemas/UserProfile"
    UserUpdateRequest:
      type: object
      properties:
        email:
          type: string
          example: "user-1@example.com"
          description: sets new user email address
          minLength: 3
        user_profile_attributes:
          $ref: "#/components/schemas/UserProfile"
    UserProfile:
      type: object
      required:
        - display_name
      properties:
        display_name:
          string: string
          minLength: 3
          maxLength: 32
          description: The anonymous profile name of the user
          example: "Awesome user"
        field_a:
          type: string
          nullable: true
          description: District within the users city, automatically set by the backend
        field_b:
          type: string
          nullable: true
          description: District within the users city, automatically set by the backend
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string